version: '3.8'
services:
  webapi:
    build:
      context: ../
      dockerfile: /Dockerfile
    container_name: test-webapi
    restart: unless-stopped
    ports:
      - 5000:80
    networks:
      - testnet
  
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

networks:
  testnet:
    name: testnet
    external: true